// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'utils.dart';

class Memory {
  final Storage totalMemory;
  final Storage usedMemory;
  final Storage totalSwap;
  final Storage usedSwap;
  final Map<int, ProcessMemoryInfo> processes;

  const Memory({
    required this.totalMemory,
    required this.usedMemory,
    required this.totalSwap,
    required this.usedSwap,
    required this.processes,
  });

  @override
  int get hashCode =>
      totalMemory.hashCode ^
      usedMemory.hashCode ^
      totalSwap.hashCode ^
      usedSwap.hashCode ^
      processes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Memory &&
          runtimeType == other.runtimeType &&
          totalMemory == other.totalMemory &&
          usedMemory == other.usedMemory &&
          totalSwap == other.totalSwap &&
          usedSwap == other.usedSwap &&
          processes == other.processes;
}

class ProcessMemoryInfo {
  final Storage memory;
  final BigInt rawMemory;
  final String name;
  final String? exe;

  const ProcessMemoryInfo({
    required this.memory,
    required this.rawMemory,
    required this.name,
    this.exe,
  });

  @override
  int get hashCode =>
      memory.hashCode ^ rawMemory.hashCode ^ name.hashCode ^ exe.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessMemoryInfo &&
          runtimeType == other.runtimeType &&
          memory == other.memory &&
          rawMemory == other.rawMemory &&
          name == other.name &&
          exe == other.exe;
}
