// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'utils.dart';

class Memory {
  final Storage totalMemory;
  final Storage usedMemory;
  final Storage totalSwap;
  final Storage usedSwap;

  const Memory({
    required this.totalMemory,
    required this.usedMemory,
    required this.totalSwap,
    required this.usedSwap,
  });

  @override
  int get hashCode =>
      totalMemory.hashCode ^
      usedMemory.hashCode ^
      totalSwap.hashCode ^
      usedSwap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Memory &&
          runtimeType == other.runtimeType &&
          totalMemory == other.totalMemory &&
          usedMemory == other.usedMemory &&
          totalSwap == other.totalSwap &&
          usedSwap == other.usedSwap;
}
