// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Storage {
  final BigInt quotient;
  final BigInt remainder;
  final Unit unit;

  const Storage({
    required this.quotient,
    required this.remainder,
    required this.unit,
  });

  @override
  int get hashCode => quotient.hashCode ^ remainder.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Storage &&
          runtimeType == other.runtimeType &&
          quotient == other.quotient &&
          remainder == other.remainder &&
          unit == other.unit;
}

enum Unit {
  b,
  kb,
  mb,
  gb,
  tb,
  pb,
  ;
}
