// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../memory.dart';
import '../utils.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Memory getMemoryInfo() => RustLib.instance.api.crateApiMemoryGetMemoryInfo();

(double, Unit) storageToFloat({required Storage storage}) =>
    RustLib.instance.api.crateApiMemoryStorageToFloat(storage: storage);

String unitToString({required Unit unit}) =>
    RustLib.instance.api.crateApiMemoryUnitToString(unit: unit);
